### ISSUE TITLE
关于函数的扩展的 λ演算 部分

### ISSUE THREAD

**Issue by CaiSijian** [wangdoc/es6-tutorial#20]
// λ演算的写法
fix = λf.(λx.f(λv.x(x)(v)))(λx.f(λv.x(x)(v)))

// ES6的写法
var fix = f => (x => f(v => x(x)(v)))
               (x => f(v => x(x)(v)));
我对于上面的代码，存在问题。
首先，第一部分，直接复制进入，发现会报错“应为标识符。”
其次，第二部分，希望有个较为不错的解释，我尝试
fix((v) => {
  console.log(v())
})
这样调用会报错“Maximum call stack size exceeded”，很不理解，希望作者能有所改善。
非常感谢。你的书很棒，故此我希望它能更加完美。

**Comment by ruanyf** [comment]
这段代码不是为了运行，而是为了演示，λ 演算与箭头函数之间存在对应关系，可以方便地改写成另一种形式。

例子改成 函数 f(x)= x + 2 用 λ 演算表示为 λx.x + 2，写成箭头函数则为 x => x + 2。
