### ISSUE TITLE
关于《23.Class 的继承》部分的建议

### ISSUE THREAD

**Issue by CaiSijian** [wangdoc/es6-tutorial#21]
新年快乐！
希望采用导图表示这些关系，理由是文字解析这些关系总是让人难懂（和作者文采没有关系，作者文采已经很棒了）。
我用mindmaster画了一幅图，
![JS类的原型链](https://github.com/wangdoc/es6-tutorial/assets/112552123/2186a771-8006-4081-8c7a-7eab17d2569e)
如果作者觉得可以，希望采纳。
这是一本很棒的书，以至于新春之日，都不忘拜读。阅读此书真是一大乐趣。

**Comment by ruanyf** [comment]
暂时不会加入插图。
