### ISSUE TITLE
关于数组的部分提案的更新

### ISSUE THREAD

**Issue by LightQuanta** [wangdoc/es6-tutorial#22]
[实例方法：toReversed()，toSorted()，toSpliced()，with()](https://wangdoc.com/es6/array#%E5%AE%9E%E4%BE%8B%E6%96%B9%E6%B3%95toreversedtosortedtosplicedwith) 的相关提案 [Change Array by copy](https://github.com/tc39/proposal-change-array-by-copy) 已于2023年3月12日[被合并进ECMAScript标准](https://github.com/tc39/ecma262/pull/2997)

[实例方法：group()，groupToMap()](https://wangdoc.com/es6/array#%E5%AE%9E%E4%BE%8B%E6%96%B9%E6%B3%95groupgrouptomap) 的相关提案 [proposal-array-grouping](https://github.com/tc39/proposal-array-grouping) 已于2023年12月5日[被合并进ECMAScript标准](https://github.com/tc39/ecma262/pull/3176) （注意该提案里的使用方法已经发生了改变，和网页里展示的不一样，`group`和`groupToMap`目前分别是`Object`和`Map`的自带方法而不是`Array`的）

部分相关链接
- [23.1.3.33 Array.prototype.toReversed()](https://tc39.es/ecma262/#sec-array.prototype.toreversed)
- [20.1.2.13 Object.groupBy(items, callbackfn)](https://tc39.es/ecma262/#sec-object.groupby)
- [24.1.2.1 Map.groupBy(items, callbackfn)](https://tc39.es/ecma262/#sec-map.groupby)

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
