### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by boyzzy1995** [wangdoc/es6-tutorial#3]
网道的字体是16px感觉有点大，能不能改成14px。还有底部能不能加一个返回顶部的按钮。

**Comment by ruanyf** [comment]
主栏的宽度比较大，14px 的字体会让一行文字过多，不利于网页阅读。

后面考虑缩小主栏宽度，再把字体改成14px。

鼠标悬浮在标题栏上，就会出现“返回顶部”的按钮。
