### ISSUE TITLE
修正几处小笔误和一点小建议

### ISSUE THREAD

**Issue by allen05ren** [wangdoc/es6-tutorial#4]
1. 此处 **function1** 后面多了一个数字 1
> (async function1 main() {

https://github.com/wangdoc/es6-tutorial/blame/master/docs/async.md#L755

2. 此处 **unusued** 字母 e 前面多了一个字母 u
> var unusued = 'I have no purpose!';

https://github.com/wangdoc/es6-tutorial/blame/master/docs/style.md#L500

3. 此处的输出应为 0 1 2，而不是 1 2 3
> ```   
>     it.next().value.then(o => console.log(o)) // 1
>     it.next().value.then(o => console.log(o)) // 2
>     it.next().value.then(o => console.log(o)) // 3
>```

https://github.com/wangdoc/es6-tutorial/blame/master/docs/async-iterator.md#L66

4. 以下两处的示例代码应该包在一个 async 函数里
```javascript
const asyncIterable = createAsyncIterable(['a', 'b']);
const asyncIterator = asyncIterable[Symbol.asyncIterator]();
const [{value: v1}, {value: v2}] = await Promise.all([
  asyncIterator.next(), asyncIterator.next()
]);
console.log(v1, v2); // a b
```
https://github.com/wangdoc/es6-tutorial/blame/master/docs/async-iterator.md#L135

```javascript
const writer = openFile('someFile.txt');
writer.next('hello'); // 立即执行
writer.next('world'); // 立即执行
await writer.return(); // 等待写入结束
```

https://github.com/wangdoc/es6-tutorial/blame/master/docs/async-iterator.md#L425

5. 以下两处的 **SharedBuffer** 确切地应该改为 **SharedArrayBuffer**，另外变量 `sharedArray[index]` 的名称没有和下面 `Atomics.load` 和 `Atomics.store` 里的 `array` 对应上，建议把下面的 `array` 改为 `sharedArray`，下文也大量使用了 `sharedArray` 变量名做演示
```javascript
Atomics.load(array, index)
Atomics.store(array, index, value)
```

> `store`方法接受三个参数：SharedBuffer 的视图、位置索引和值，返回`sharedArray[index]`的值。`load`方法只接受两个参数：SharedBuffer 的视图和位置索引，也是返回`sharedArray[index]`的值。

6. 此处的 **移出模块** 和 **模块内部** 的 **模块** 应该是指 **类**，**移除类** 和 **模块内部**，下方的演示代码整体指 **模块**，“所有方法都是对外可见的“指的是此模块会导出此 **类** 吧。

> 另一种方法就是索性将私有方法移出模块，因为模块内部的所有方法都是对外可见的。

```javascript
class Widget {
  foo (baz) {
    bar.call(this, baz);
  }
  // ...
}
function bar(baz) {
  return this.snaf = baz;
}
```

> 上面代码中，`foo`是公开方法，内部调用了`bar.call(this, baz)`。这使得`bar`实际上成为了当前模块的私有方法。

https://github.com/wangdoc/es6-tutorial/blame/master/docs/class.md#L740

7. 下方的 “同一个`my_module`**实例**，应为同一个`my_module`**模块**吧

> 上面代码中，虽然`foo`和`bar`在两个语句中加载，但是它们对应的是同一个`my_module`实例。也就是说，`import`语句是 Singleton 模式。

https://github.com/wangdoc/es6-tutorial/blame/master/docs/module.md#L289

8. 以下几段示例代码的变量名 **Thunk** 建议改个名，如 **toThunk**，理由是 Thunk 函数实际指的是使用  **Thunk** 转换后的函数，直接使用  **Thunk** 容易让人以为它才是  Thunk 函数。就如后文介绍的 thunkify，字面意思就代表它是一个转换函数，转换后的函数是 Thunk 函数。

JavaScript 语言是传值调用，它的 Thunk 函数含义有所不同。在 JavaScript 语言中，Thunk 函数替换的不是表达式，而是多参数函数，将其替换成一个只接受回调函数作为参数的单参数函数。

```javascript
// 正常版本的readFile（多参数版本）
fs.readFile(fileName, callback);
// Thunk版本的readFile（单参数版本）
var Thunk = function (fileName) {
  return function (callback) {
    return fs.readFile(fileName, callback);
  };
};
var readFileThunk = Thunk(fileName);
readFileThunk(callback);
```

上面代码中，`fs`模块的`readFile`方法是一个多参数函数，两个参数分别为文件名和回调函数。经过转换器处理，它变成了一个单参数函数，只接受回调函数作为参数。这个单参数版本，就叫做 Thunk 函数。

任何函数，只要参数有回调函数，就能写成 Thunk 函数的形式。下面是一个简单的 Thunk 函数转换器。

```javascript
// ES5版本
var Thunk = function(fn){
  return function (){
    var args = Array.prototype.slice.call(arguments);
    return function (callback){
      args.push(callback);
      return fn.apply(this, args);
    }
  };
};
// ES6版本
const Thunk = function(fn) {
  return function (...args) {
    return function (callback) {
      return fn.call(this, ...args, callback);
    }
  };
};
```

使用上面的转换器，生成`fs.readFile`的 Thunk 函数。

```javascript
var readFileThunk = Thunk(fs.readFile);
readFileThunk(fileA)(callback);
```

下面是另一个完整的例子。

```javascript
function f(a, cb) {
  cb(a);
}
const ft = Thunk(f);
ft(1)(console.log) // 1
```
https://github.com/wangdoc/es6-tutorial/blame/master/docs/generator-async.md#L287

9. 以下的 “一旦遇到`await`就会先**返回**”，这里的 **返回** 改成 **暂停** 更准确，或者改成 “一旦遇到`await`就会先等到其后异步操作完成，再接着执行函数体内后面的语句。”

> `async`函数返回一个 Promise 对象，可以使用`then`方法添加回调函数。当函数执行的时候，一旦遇到`await`就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。

https://github.com/wangdoc/es6-tutorial/blame/master/docs/async.md#L72

10. 最后一点小建议
整书里有好几处作为知识点后的演示案例，使用 **实例** 来代表示例，建议改用 **示例** 或 **应用案例** 等来表述，以免和书中大量出现的 **实例对象** 的实例混淆。这个主要出现在章节的标题，另外其他一些地方也偶有出现。另外，JavaScript 教程 那本书中也出现了几处。

**Comment by allen05ren** [comment]
是我理解有误

**Comment by ruanyf** [comment]
谢谢指出，除了有几个地方，其他都改了。

4、那两段都是伪代码，顶层`await`也马上就写入标准，而且不放入 async 整个代码更容易读，所以不改了。

8、我觉得 Thunk 不影响理解，语义也没问题，当然 toThunk 的语义可能更好一些，但是 Thunk 简洁也能表达意图，所以不改了。

9、“返回”的意思是，代码的执行权返回给函数外面的代码，而且函数并没有“暂停”，实际上是在等异步代码的结果返回。所以，这段我觉得没错。

10、我以后注意，统一称为“示例”。

**Comment by allen05ren** [comment]
```javascript
Atomics.load(typedArray, index)
Atomics.store(typedArray, index, value)
```
第五点这里没改对，应该把 `typedArray` 换成 `sharedArray`，后文的类似演示代码大量使用了这个变量名作为 SharedArrayBuffer 的视图的实例，它可能是 TypedArray 视图或 DataView 视图的实例。相应的下面的两个 `sharedArrayBuffer[index]` 对应换成 `sharedArray[index]` （前后文能对的上）：
```javascript
Atomics.load(sharedArray, index)
Atomics.store(sharedArray, index, value)
```
`store`方法接受三个参数：SharedArrayBuffer 的视图、位置索引和值，返回`sharedArray[index]`的值。`load`方法只接受两个参数：SharedArrayBuffer 的视图和位置索引，也是返回`sharedArray[index]`的值。

**Comment by ruanyf** [comment]
`typedArray`是写在标准里面的。https://tc39.es/ecma262/#sec-atomics.load

**Comment by allen05ren** [comment]
@ruanyf 
那应该把下文对应的两个 `sharedArrayBuffer[index]` 换成 `typedArray[index]`，以便与前文的 `Atomics.load` 和 `Atomics.store` 方法内的参数名保持一致。

**Comment by ruanyf** [comment]
这里可以改，已经改好了。
