### ISSUE TITLE
扩展运算符的应用 合并数组 第二种并不是浅拷贝

### ISSUE THREAD

**Issue by hyc3z** [wangdoc/es6-tutorial#6]
> （2）合并数组
> 
> 扩展运算符提供了数组合并的新写法。
> 
> const arr1 = ['a', 'b'];
> const arr2 = ['c'];
> const arr3 = ['d', 'e'];
> 
> // ES5 的合并数组
> arr1.concat(arr2, arr3);
> // [ 'a', 'b', 'c', 'd', 'e' ]
> 
> // ES6 的合并数组
> [...arr1, ...arr2, ...arr3]
> // [ 'a', 'b', 'c', 'd', 'e' ]
> 不过，这两种方法都是浅拷贝，使用的时候需要注意。
> 

实际情况：Node@10 or node@15
```
const arr1 = ['a', 'b'];
const arr2 = ['c'];
const arr3 = ['d', 'e'];
const arr4 = [...arr1, ...arr2, ...arr3]
arr3[0] = "S"
console.log(arr3, arr4)// [ 'S', 'e' ] [ 'a', 'b', 'c', 'd', 'e' ]
```

**Comment by ruanyf** [comment]
const arr1 = [['a'，'b']];
